apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
  namespace: network-operator
spec:
  ofedDriver:
    env:
    - name: RESTORE_DRIVER_ON_POD_TERMINATION
      value: 'true'
    - name: UNLOAD_STORAGE_MODULES
      value: 'true'
    - name: CREATE_IFNAMES_UDEV
      value: 'true'
    # When using internal air-gapped registry with prepared image
    image: mofed-offline-v2
    repository: CONTAINERS_REGISTRY/openshift/nvidia
    version: "23.04–0.5.3.3.1"
    # end of air-gapped section 
    upgradePolicy:
      autoUpgrade: true
      maxParallelUpgrades: 1
      drain:
        enable: true
        force: false
        podSelector: ""
        timeoutSeconds: 300
        deleteEmptyDir: false
